### PR TITLE
Add option to control deployer timeout

### LINKED ISSUE #49: Add option to tests.yaml to control deployer timeout
Some larger bundles (big data, openstack) take longer than the default 45 minutes to deploy and reach a stable state.  There should be a `tests.yaml` option to increase that.

### PR DESCRIPTION
**Pull request by johnsca**
Fixes #49

### CODE REVIEW

**Comment by seman** [comment]
Minor suggestion, change it to "deployment_timeout" so that it makes sense if we use it for a native `deploy` too. Thank you.

LGTM.

**Comment by kwmonroe** [comment]
drive by LGTM.  all the words appear to be spelled correctly.

**Comment by johnsca** [comment]
Changed to `deployment_timeout`

**Comment by tvansteenburgh** [comment]
This looks great, thanks. Please also update the tests.yaml section  of the README to document this new config option.

**Comment by johnsca** [comment]
Updated the README

**Pull request merged**
